spring:
  datasource:
    url: jdbc:h2:mem:jokedb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
logging:
  level:
    org.springframework: ERROR
    com.example.myjokeapi: DEBUG