openapi: 3.0.0
info:
  title: My Joke API
  description: >-
    This is a sample `Joke` server, where you can get random jokes, or search jokes by ID or term.
    <br>The main endpoints contain only dad jokes for now. They come directly from an Open API and converted to JokeDto objects.
    <br>If random jokes are searched, they are saved in the local in-memory database.
    
    Support:
  contact:
    name: Cs Doe
    email: cs.doe@example.com
  version: 1.0.0-oas3
servers:
  - url: http://localhost:8080/jokes
    description: Local server
security: [] #No security
tags:
  - name: dadjokes
    externalDocs:
      description: Originally from icanhazdadjoke API
      url: https://icanhazdadjoke.com/
  - name: dbOperations
paths:
  /random:
    get:
      tags:
        - dadjokes
      summary: Provides with a random joke
      operationId: getRandom
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JokeDto'
        '400':
          description: Invalid status value
  /{id}:
    get:
      tags:
        - dadjokes
      summary: Searches a joke by ID
      operationId: findById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JokeDto'
        '400':
          description: Invalid status value
  /:
    get:
      tags:
        - dadjokes
        - dbOperations
      summary: Searches jokes by term, by category, or if none of them is given then returns all jokes in DB
      operationId: searchFor
      parameters:
        - in: query
          name: term
          required: false
          schema:
            type: string
          description: It searches on the dadjokes server
        - in: query
          name: category
          required: false
          schema:
            type: string
          description: It searches in the local database
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JokeDto'
        '400':
          description: Invalid status value
    post:
      tags:
        - dbOperations
      summary: Adds a new joke to the local database
      operationId: addJoke
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JokeDto'
      responses:
        '201':
          description: Created
components:
  schemas:
    JokeDto:
      type: object
      properties:
        joke:
          type: string
          example: When my wife told me to stop impersonating a flamingo, I had to put my foot down.
        category:
          type: string
          example: dadjoke / officejoke / ...
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header